//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Settings/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Generation"",
            ""id"": ""67088816-efc9-4025-8bc8-3ad6928b8257"",
            ""actions"": [
                {
                    ""name"": ""Generate"",
                    ""type"": ""Button"",
                    ""id"": ""62683a71-4ff0-48b3-9573-852db844a6a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Clear"",
                    ""type"": ""Button"",
                    ""id"": ""05d78e74-f323-45ba-9fec-89f9881a507f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Generate_City"",
                    ""type"": ""Button"",
                    ""id"": ""699cd884-6499-45a8-9420-2bb8e6ae88d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Generate_Street"",
                    ""type"": ""Button"",
                    ""id"": ""95944b33-6295-4843-987c-64d543e509e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Generate_Park"",
                    ""type"": ""Button"",
                    ""id"": ""db04d582-44fb-4819-9ef9-4fb3edc6d62f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Generate_Factory"",
                    ""type"": ""Button"",
                    ""id"": ""591547af-6bf5-4f76-8edd-0b08aef13f7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Generate_Wall"",
                    ""type"": ""Button"",
                    ""id"": ""8d68e32b-fcd8-4cb4-b649-961c08d0d464"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""723b4bbc-6538-4c88-92c7-8c5547636622"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c321553b-953d-4003-9f7c-7b73752be65f"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Generate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3799854-751f-4c16-b404-6c48a349c56f"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a611cb61-7f13-4c61-9925-54a9f7657fa1"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Generate_Wall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be01f25f-9c06-4369-a4ca-05b7187bf8a1"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Generate_Factory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""981a7682-1b68-4819-b024-80f20fd5cdc6"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Generate_City"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""405da05d-15c0-4d39-a6be-2def157781fe"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Generate_Street"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2769969-5f9c-4473-bcf8-180b7e0b3e2f"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Generate_Park"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7a0f886-5a23-4149-8037-0b74d4721c3f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f92a8ee2-2685-4ae9-bfda-17dfbc4ed840"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Generation
        m_Generation = asset.FindActionMap("Generation", throwIfNotFound: true);
        m_Generation_Generate = m_Generation.FindAction("Generate", throwIfNotFound: true);
        m_Generation_Clear = m_Generation.FindAction("Clear", throwIfNotFound: true);
        m_Generation_Generate_City = m_Generation.FindAction("Generate_City", throwIfNotFound: true);
        m_Generation_Generate_Street = m_Generation.FindAction("Generate_Street", throwIfNotFound: true);
        m_Generation_Generate_Park = m_Generation.FindAction("Generate_Park", throwIfNotFound: true);
        m_Generation_Generate_Factory = m_Generation.FindAction("Generate_Factory", throwIfNotFound: true);
        m_Generation_Generate_Wall = m_Generation.FindAction("Generate_Wall", throwIfNotFound: true);
        m_Generation_Quit = m_Generation.FindAction("Quit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Generation
    private readonly InputActionMap m_Generation;
    private IGenerationActions m_GenerationActionsCallbackInterface;
    private readonly InputAction m_Generation_Generate;
    private readonly InputAction m_Generation_Clear;
    private readonly InputAction m_Generation_Generate_City;
    private readonly InputAction m_Generation_Generate_Street;
    private readonly InputAction m_Generation_Generate_Park;
    private readonly InputAction m_Generation_Generate_Factory;
    private readonly InputAction m_Generation_Generate_Wall;
    private readonly InputAction m_Generation_Quit;
    public struct GenerationActions
    {
        private @InputActions m_Wrapper;
        public GenerationActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Generate => m_Wrapper.m_Generation_Generate;
        public InputAction @Clear => m_Wrapper.m_Generation_Clear;
        public InputAction @Generate_City => m_Wrapper.m_Generation_Generate_City;
        public InputAction @Generate_Street => m_Wrapper.m_Generation_Generate_Street;
        public InputAction @Generate_Park => m_Wrapper.m_Generation_Generate_Park;
        public InputAction @Generate_Factory => m_Wrapper.m_Generation_Generate_Factory;
        public InputAction @Generate_Wall => m_Wrapper.m_Generation_Generate_Wall;
        public InputAction @Quit => m_Wrapper.m_Generation_Quit;
        public InputActionMap Get() { return m_Wrapper.m_Generation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GenerationActions set) { return set.Get(); }
        public void SetCallbacks(IGenerationActions instance)
        {
            if (m_Wrapper.m_GenerationActionsCallbackInterface != null)
            {
                @Generate.started -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate;
                @Generate.performed -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate;
                @Generate.canceled -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate;
                @Clear.started -= m_Wrapper.m_GenerationActionsCallbackInterface.OnClear;
                @Clear.performed -= m_Wrapper.m_GenerationActionsCallbackInterface.OnClear;
                @Clear.canceled -= m_Wrapper.m_GenerationActionsCallbackInterface.OnClear;
                @Generate_City.started -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_City;
                @Generate_City.performed -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_City;
                @Generate_City.canceled -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_City;
                @Generate_Street.started -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Street;
                @Generate_Street.performed -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Street;
                @Generate_Street.canceled -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Street;
                @Generate_Park.started -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Park;
                @Generate_Park.performed -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Park;
                @Generate_Park.canceled -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Park;
                @Generate_Factory.started -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Factory;
                @Generate_Factory.performed -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Factory;
                @Generate_Factory.canceled -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Factory;
                @Generate_Wall.started -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Wall;
                @Generate_Wall.performed -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Wall;
                @Generate_Wall.canceled -= m_Wrapper.m_GenerationActionsCallbackInterface.OnGenerate_Wall;
                @Quit.started -= m_Wrapper.m_GenerationActionsCallbackInterface.OnQuit;
                @Quit.performed -= m_Wrapper.m_GenerationActionsCallbackInterface.OnQuit;
                @Quit.canceled -= m_Wrapper.m_GenerationActionsCallbackInterface.OnQuit;
            }
            m_Wrapper.m_GenerationActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Generate.started += instance.OnGenerate;
                @Generate.performed += instance.OnGenerate;
                @Generate.canceled += instance.OnGenerate;
                @Clear.started += instance.OnClear;
                @Clear.performed += instance.OnClear;
                @Clear.canceled += instance.OnClear;
                @Generate_City.started += instance.OnGenerate_City;
                @Generate_City.performed += instance.OnGenerate_City;
                @Generate_City.canceled += instance.OnGenerate_City;
                @Generate_Street.started += instance.OnGenerate_Street;
                @Generate_Street.performed += instance.OnGenerate_Street;
                @Generate_Street.canceled += instance.OnGenerate_Street;
                @Generate_Park.started += instance.OnGenerate_Park;
                @Generate_Park.performed += instance.OnGenerate_Park;
                @Generate_Park.canceled += instance.OnGenerate_Park;
                @Generate_Factory.started += instance.OnGenerate_Factory;
                @Generate_Factory.performed += instance.OnGenerate_Factory;
                @Generate_Factory.canceled += instance.OnGenerate_Factory;
                @Generate_Wall.started += instance.OnGenerate_Wall;
                @Generate_Wall.performed += instance.OnGenerate_Wall;
                @Generate_Wall.canceled += instance.OnGenerate_Wall;
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
            }
        }
    }
    public GenerationActions @Generation => new GenerationActions(this);
    public interface IGenerationActions
    {
        void OnGenerate(InputAction.CallbackContext context);
        void OnClear(InputAction.CallbackContext context);
        void OnGenerate_City(InputAction.CallbackContext context);
        void OnGenerate_Street(InputAction.CallbackContext context);
        void OnGenerate_Park(InputAction.CallbackContext context);
        void OnGenerate_Factory(InputAction.CallbackContext context);
        void OnGenerate_Wall(InputAction.CallbackContext context);
        void OnQuit(InputAction.CallbackContext context);
    }
}
